version: "3"
services:
  web:
    image: nginx:1.13
    container_name: websocket
    ports:
      - 8090:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ws

networks:
  ws: